### ISSUE TITLE
举手

### ISSUE THREAD

**Issue by foreverbig** [fgksgf/Legend-of-Sword-and-Fairy#1]
这是用什么软件写的？素材在哪找的？

**Comment by fgksgf** [comment]
java语言写的，主要用的swing库来写UI，素材是老师提供的

**Comment by foreverbig** [comment]
这个好简单的感觉，有没有更新呢？至少加个打怪系统之类的？

**Comment by fgksgf** [comment]
因为素材有限，只写了这么多。这个项目主要的目的还是提供一个写游戏的思路和框架，读懂了代码，再去写其他游戏都是类似的原理了。
